import Head from 'next/head'
import { FC, PropsWithChildren } from 'react'
import style from './PageLayout.module.scss'
import { Roboto } from 'next/font/google'
import Header from '@/components/Header/Header'

interface IProps {
  className?: string
}

const PageLayout: FC<PropsWithChildren<IProps>> = ({
  children,
  className = '',
}) => {
  return (
    <>
      <Head>
        <title>ПроCAR</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main className={`${style.wrapper} ${className}`}>{children}</main>
    </>
  )
}

export default PageLayout
